// <auto-generated />
using System;
using FormulaOnce.Events.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaOnce.Events.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20260104161201_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Events")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormulaOnce.Events.Domain.Circuit.Circuit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Circuits", "Events");
                });

            modelBuilder.Entity("FormulaOnce.Events.Domain.Race.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CircuitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfLaps")
                        .HasColumnType("int");

                    b.Property<double>("RaceDistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CircuitId");

                    b.ToTable("Races", "Events");
                });

            modelBuilder.Entity("FormulaOnce.Events.Domain.Race.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceSessions", "Events");
                });

            modelBuilder.Entity("FormulaOnce.Events.Domain.Circuit.Circuit", b =>
                {
                    b.OwnsOne("FormulaOnce.Events.Domain.Circuit.CircuitRecord", "LapRecord", b1 =>
                        {
                            b1.Property<Guid>("CircuitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("DriverName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DriverName");

                            b1.Property<TimeSpan>("Time")
                                .HasColumnType("time")
                                .HasColumnName("LapTime");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("CircuitId");

                            b1.ToTable("CircuitLapRecords", "Events");

                            b1.WithOwner()
                                .HasForeignKey("CircuitId");
                        });

                    b.OwnsOne("FormulaOnce.Events.Domain.Circuit.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("CircuitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Country");

                            b1.HasKey("CircuitId");

                            b1.ToTable("Circuits", "Events");

                            b1.WithOwner()
                                .HasForeignKey("CircuitId");

                            b1.OwnsOne("FormulaOnce.Events.Domain.Circuit.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationCircuitId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("float")
                                        .HasColumnName("Longitude");

                                    b2.HasKey("LocationCircuitId");

                                    b2.ToTable("Circuits", "Events");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationCircuitId");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.OwnsMany("FormulaOnce.Events.Domain.Circuit.TrackLandmark", "Landmarks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CircuitId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("LandmarkType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("NearTurn")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("CircuitId");

                            b1.ToTable("CircuitLandmarks", "Events");

                            b1.WithOwner()
                                .HasForeignKey("CircuitId");
                        });

                    b.Navigation("Landmarks");

                    b.Navigation("LapRecord");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaOnce.Events.Domain.Race.Race", b =>
                {
                    b.HasOne("FormulaOnce.Events.Domain.Circuit.Circuit", "Circuit")
                        .WithMany()
                        .HasForeignKey("CircuitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Circuit");
                });

            modelBuilder.Entity("FormulaOnce.Events.Domain.Race.Session", b =>
                {
                    b.HasOne("FormulaOnce.Events.Domain.Race.Race", null)
                        .WithMany("Sessions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaOnce.Events.Domain.Race.Race", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
