// <auto-generated />
using System;
using FormulaOnce.Teams.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaOnce.Teams.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TeamsDbContext))]
    partial class TeamsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Teams")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormulaOnce.Teams.Domain.Constructor.Constructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstablishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Constructors", "Teams");
                });

            modelBuilder.Entity("FormulaOnce.Teams.Domain.Driver.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<Guid>("ConstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RacingNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConstructorId");

                    b.ToTable("Drivers", "Teams");
                });

            modelBuilder.Entity("FormulaOnce.Teams.Domain.Constructor.Constructor", b =>
                {
                    b.OwnsOne("FormulaOnce.Teams.Domain.Constructor.ConstructorStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("ConstructorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("ConstructorId");

                            b1.ToTable("ConstructorStatistics", "Teams");

                            b1.WithOwner()
                                .HasForeignKey("ConstructorId");

                            b1.OwnsOne("FormulaOnce.Teams.Domain.Constructor.AllTimeSummary", "AllTimeSummary", b2 =>
                                {
                                    b2.Property<Guid>("ConstructorStatsConstructorId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("GrandPrixEntered")
                                        .HasColumnType("int");

                                    b2.Property<string>("HighestGridPosition")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<string>("HighestRaceFinish")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<int>("Podiums")
                                        .HasColumnType("int");

                                    b2.Property<int>("PolePositions")
                                        .HasColumnType("int");

                                    b2.Property<int>("TeamPoints")
                                        .HasColumnType("int");

                                    b2.Property<int>("WorldChampionships")
                                        .HasColumnType("int");

                                    b2.HasKey("ConstructorStatsConstructorId");

                                    b2.ToTable("ConstructorAllTimeStatistics", "Teams");

                                    b2.WithOwner()
                                        .HasForeignKey("ConstructorStatsConstructorId");
                                });

                            b1.OwnsOne("FormulaOnce.Teams.Domain.Constructor.SeasonStats", "SeasonStats", b2 =>
                                {
                                    b2.Property<Guid>("ConstructorStatsConstructorId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("DNFs")
                                        .HasColumnType("int");

                                    b2.Property<int>("DhlFastestLaps")
                                        .HasColumnType("int");

                                    b2.Property<int>("SeasonPoints")
                                        .HasColumnType("int");

                                    b2.Property<int>("SeasonPosition")
                                        .HasColumnType("int");

                                    b2.HasKey("ConstructorStatsConstructorId");

                                    b2.ToTable("ConstructorSeasonStatistics", "Teams");

                                    b2.WithOwner()
                                        .HasForeignKey("ConstructorStatsConstructorId");

                                    b2.OwnsOne("FormulaOnce.Teams.Domain.Constructor.GrandPrixStats", "GrandPrixStats", b3 =>
                                        {
                                            b3.Property<Guid>("SeasonStatsConstructorStatsConstructorId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("GrandPrixPodiums")
                                                .HasColumnType("int");

                                            b3.Property<int>("GrandPrixPoints")
                                                .HasColumnType("int");

                                            b3.Property<int>("GrandPrixPoles")
                                                .HasColumnType("int");

                                            b3.Property<int>("GrandPrixRaces")
                                                .HasColumnType("int");

                                            b3.Property<int>("GrandPrixTop10s")
                                                .HasColumnType("int");

                                            b3.Property<int>("GrandPrixWins")
                                                .HasColumnType("int");

                                            b3.HasKey("SeasonStatsConstructorStatsConstructorId");

                                            b3.ToTable("GrandPrixStatistics", "Teams");

                                            b3.WithOwner()
                                                .HasForeignKey("SeasonStatsConstructorStatsConstructorId");
                                        });

                                    b2.OwnsOne("FormulaOnce.Teams.Domain.Constructor.SprintStats", "SprintStats", b3 =>
                                        {
                                            b3.Property<Guid>("SeasonStatsConstructorStatsConstructorId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("SprintPodiums")
                                                .HasColumnType("int");

                                            b3.Property<int>("SprintPoints")
                                                .HasColumnType("int");

                                            b3.Property<int>("SprintPoles")
                                                .HasColumnType("int");

                                            b3.Property<int>("SprintRaces")
                                                .HasColumnType("int");

                                            b3.Property<int>("SprintTop10s")
                                                .HasColumnType("int");

                                            b3.Property<int>("SprintWins")
                                                .HasColumnType("int");

                                            b3.HasKey("SeasonStatsConstructorStatsConstructorId");

                                            b3.ToTable("SprintStatistics", "Teams");

                                            b3.WithOwner()
                                                .HasForeignKey("SeasonStatsConstructorStatsConstructorId");
                                        });

                                    b2.Navigation("GrandPrixStats")
                                        .IsRequired();

                                    b2.Navigation("SprintStats")
                                        .IsRequired();
                                });

                            b1.Navigation("AllTimeSummary")
                                .IsRequired();

                            b1.Navigation("SeasonStats")
                                .IsRequired();
                        });

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("FormulaOnce.Teams.Domain.Driver.Driver", b =>
                {
                    b.HasOne("FormulaOnce.Teams.Domain.Constructor.Constructor", "Constructor")
                        .WithMany("Drivers")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FormulaOnce.Teams.Domain.Driver.DriverStats", "CareerDriverStats", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("TotalChampionships")
                                .HasColumnType("int");

                            b1.Property<int>("TotalPodiums")
                                .HasColumnType("int");

                            b1.Property<int>("TotalPoles")
                                .HasColumnType("int");

                            b1.Property<int>("TotalRaces")
                                .HasColumnType("int");

                            b1.Property<int>("TotalWins")
                                .HasColumnType("int");

                            b1.HasKey("DriverId");

                            b1.ToTable("DriverStatistics", "Teams");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("CareerDriverStats")
                        .IsRequired();

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("FormulaOnce.Teams.Domain.Constructor.Constructor", b =>
                {
                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
